info:
  title: Demo API
  description: An API used for demo purposes
  termsOfService: http://example.com/terms
  contact:
    name: Demo API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1